version: '3.9'

volumes:
  mongodata:

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "pip install -r requirements.txt && python main.py"
    restart: always
    env_file:
      - .env


