apiVersion: v1
kind: Service
metadata:
  name: bachelor-api-service
spec:
  selector:
    app: bachelor-api
  ports:
    - port: 8000
      targetPort: 8000
  externalTrafficPolicy: Cluster
  type: LoadBalancer