apiVersion: apps/v1
kind: Deployment
metadata:
  name: bachelor-api-deployment
  labels:
    app: bachelor-api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: <secret-name>
