apiVersion: apps/v1
kind: Deployment
metadata:
  name: bachelor-api-deployment
  labels:
    app: bachelor-api
spec:
  selector:
    matchLabels:
      app: bachelor-api
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bachelor-api
    spec:
      containers:
      - name: bachelor-api
        image: denizi/bachelor
        envFrom:
          - configMapRef:
              name: production-secrets
        ports:
        - containerPort: 8000
